sudo: required
services:
    - docker
env:
    global:
        - IMAGE_NAME=osind/pylint-odoo

    matrix:
        - DOCKER_TAG=oca
        - DOCKER_TAG=oca-beta

script:
    - ./build.sh

# after_script:
#     - docker images
#
# before_deploy:
#     - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"
#     - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
#     - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
#
# deploy:
#     provider: script
#     script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
#     on:
#         branch: master
