sudo: required
services:
    - docker
env:
    global:
        - IMAGE_NAME=osind/pylint-odoo

    matrix:
        - DOCKER_TAG=oca
        - DOCKER_TAG=oca-beta

script:
    - ./build.sh

before_deploy:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"

deploy:
    provider: script
    script: docker push "${IMAGE_NAME}:${DOCKER_TAG}"
    on:
        branch: master
