sudo: required
services:
    - docker
env:
    global:
        - IMAGE_NAME=osind/pylint-odoo

before_script:
    - version="3.0.3"
    - docker image pull "$IMAGE_NAME" || true

script:
    - docker image build --pull --cache-from "${IMAGE_NAME}" --tag "${IMAGE_NAME}" .

after_script:
    - docker images

before_deploy:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"
    - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
    - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"

deploy:
    provider: script
    script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
    on:
        branch: master
